# Configuración de Supabase
SUPABASE_URL = "https://ycxdogqjdvdsvinlvwar.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljeGRvZ3FqZHZkc3Zpbmx2d2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2OTU0NzksImV4cCI6MjA3NzI3MTQ3OX0.8Rhz02dz8ybDZyqRQGdwDkqW1YjO_2azUBCJwFXqX7U"

# APIs de Deportes
API_FOOTBALL_KEY = "67a4239bf0748aa2a9059c38c0399607"

# APIs de IA y Pagos
GOOGLE_STUDIO_KEY= "AIzaSyBFrMpt-VIVid-dz-p4waygIBV8U6iDbfA"

# Base de datos PostgreSQL para Prisma
POSTGRES_HOST = "localhost"
POSTGRES_PORT = 5432
POSTGRES_DB = "futdb"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "123456"
DATABASE_URL = "postgresql://postgres:123456@localhost:5432/futdb"

DIRECT_URL="postgresql://neondb_owner:npg_GbhITn5tv1UQ@ep-autumn-fire-ati164jy.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

# Configuración opcional
LOG_LEVEL = "info"
DEBUG_MODE = false
